### ISSUE TITLE
Rename master branch to trunk

### ISSUE THREAD

**Issue by realvarx** [atsign-foundation/private_fit#3]
**Is your feature request related to a problem? Please describe.**
No, it is just an enhacement.

**Describe the solution you'd like**
Change the name of the default branch to 'trunk' instead of 'master' in order to be consistent with the other atsign-foundation repos.

**Additional context**
It is not something to be done urgently.

**Comment by kzawadi** [comment]
@XavierChanth has fixed this.. Now we are good
