### ISSUE TITLE
Widget Overflow

### ISSUE THREAD

**Issue by bhattabhi013** [atsign-foundation/private_fit#34]
### Describe the bug

Overflow is present at widget which is causing the error.

### Steps to reproduce

1. First 'login'
2. Then check the 'home' page
3. See the error

### Expected behavior

The overflow shouldn't be there.

### Screenshots

<img width="252" alt="image" src="https://user-images.githubusercontent.com/47862474/195190208-4109c1f1-b260-4231-8b4c-bdf59051ff99.png">

### Smartphones

- Device: [e.g. Realme 5]
- OS: [e.g. Android 11]

### Were you using an atApplication when the bug was found?

No

**Comment by bhattabhi013** [comment]
I'll like to work on it.

**Comment by ghost** [comment]
done

> I'll like to work on it.
